apiVersion: v1
kind: Service
metadata:
  name: mlops-lb
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.containerPort }}