name: MLOPS Group 13 CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 Twitter_Sentiment_Indian_Election_2019/src/main --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 Twitter_Sentiment_Indian_Election_2019/src/main --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/Twitter_Sentiment_Indian_Election_2019/src" >> $GITHUB_ENV
    - name: Set environment variables
      run: |
        echo "DATA_FILE_PATH=$(pwd)/Twitter_Sentiment_Indian_Election_2019/data/Twitter_Data.csv" >> $GITHUB_ENV
        echo "PKL_FILE_PATH=$(pwd)/Twitter_Sentiment_Indian_Election_2019/pkl/best_model_twitter_senti.pkl" >> $GITHUB_ENV
    
    - name: Start MLflow server
      run: |
        nohup mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0 --port 5000 &

    - name: Run tests
      run: |
        pytest Twitter_Sentiment_Indian_Election_2019/src/tests

  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mlops_twitter_senti:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/mlops_twitter_senti:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Install gke-gcloud-auth-plugin
      run: gcloud components install gke-gcloud-auth-plugin

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }}
        kubectl config set-credentials ${{ secrets.GKE_CLUSTER_NAME }} --auth-provider=gcp

    - name: Deploy to GKE
      run: |
        helm upgrade --install mlops-release4 mlops-app/ --namespace default --set image.repository=${{ secrets.DOCKER_USERNAME }}/mlops_twitter_senti --set image.tag=latest